### ISSUE TITLE
Need more Documentation.

### ISSUE THREAD

**Issue by rjams** [svensp/hcloud_ocf#1]
I would love to check the OCF Resource FloatingIP.
I need some more Documentation to bring this resource up and running.
Are there any Details on ".env".

test.sh runs without errors.

root@app1:/usr/lib/ocf/resource.d/hetzner# ./test.sh 
.........................................................................................
----------------------------------------------------------------------
Ran 89 tests in 0.267s

The Test described in your Readme failed.
I configured a valid api-token ant the Floating IP.

root@app1:/usr/lib/ocf/resource.d/hetzner# python floating_ip start
Error: Missing parameter ip
  File "floating_ip/__main__.py", line 26, in <module>
    code = application.run(resourceAgent, api.action())
  File "floating_ip/ocf.py", line 115, in run
    self.populater.populate(resource, validate)
  File "floating_ip/common.py", line 41, in populate
    assert not value == None
An error occurred on line 41 in statement assert not value == None

Please Help to get this up and running.

**Comment by svensp** [comment]
The error you're seeing means that a required parameter was not set.
The parameter `floating_ip` was renamed to `ip` and I forgot to update the `.env.template` file, my mistake. Please check out the newest master version and try again - there also was a bug with the test host finder which is fixed there.

**Comment by rjams** [comment]
Ok, 1 step further...
I try to configure the FailoverIp with "crm", but its not accepted.
`primitive vip_floating_ip ocf:hetzner:FailoverIp \
    params ip=xxx.xxx.xxx.xxx \
    op start interval=0 timeout=20 \
    op stop interval=0 timeout=20 \
    op monitor interval=10 start-delay=0 timeout=20
`
ERROR: ocf:hetzner:FailoverIp: got no meta-data, does this RA exist?
ERROR: ocf:hetzner:FailoverIp: no such resource agent

Any Idea ?

**Comment by svensp** [comment]
I use pcs to configure pacemaker but this looks fairly similar. 2 things:
1. the api_token parameter is missing.
2. Did you make the floating_ip file executable and copied it to `/usr/lib/ocf/resource.d/hetzner/`?

**Comment by svensp** [comment]
Ah, and the file is called `floating_ip` by default so `ocf:hetzner:floating_ip` would be the correct agent name

**Comment by rjams** [comment]
OK. It works now. Thank`s for your support. 
Some extensions and cleanup in the docs and this is a very usable tool.
