### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by pbousek** [svensp/hcloud_ocf#3]
Hello,
It's more feature request than issue. It's possible to extend this ocf for ipv6 support? 

Hetzner virtual has both ipv4 and ipv6 ip and you can have ipv6 floating ip too.

Thanks

Petr

**Comment by svensp** [comment]
I checked the docs and I don't think ipv6 is handled any different than ipv4 so allowing ipv6 in the validation of the `ip` parameter should be enough to enable them. I'll allow ipv6 and build a test version but I'm not sure how soon I'll be able to test it myself.

**Comment by svensp** [comment]
I allowed ipv6 addresses in a new release named 1.1.0rc1. It is untested for now but you can give it a try if you'd like

**Comment by pbousek** [comment]
yes, thanks, I'll check it tomorrow.

**Comment by pbousek** [comment]
Hi, 
it works. I did some mistake when I read the hetzner api doc and tried to set single IP from the /64 block that hetzner assigns to you. Single IPv6 is used only when you set reverse DNS, not for assigning.
 
Before I realised that i'm wrong, i did some troubleshooting to the OCF via https://wiki.clusterlabs.org/wiki/Debugging_Resource_Failures - so it can helpful  in case of troubleshooting

/tmp/hcloud_ocf/tests/floating_ip# export OCF_RESKEY_api_token=xxxxxxtokenxxxxxx
/tmp/hcloud_ocf/tests/floating_ip# export OCF_RESKEY_ip=xxxx:xxxx:xxxx:xxxx::/64"
/tmp/hcloud_ocf/tests/floating_ip# /usr/lib/ocf/resource.d/hetzner/floating_ip start ; echo $?

So OCF should be functional.

 
Petr
