### ISSUE TITLE
Cannot parse meta-data XML

### ISSUE THREAD

**Issue by ahaase-moditech** [svensp/hcloud_ocf#6]
Hello,

running the ocf RA on a Debian 10 always fails with the abovementioned error message, when asking for ra info or trying to use the ra. I used the automatic way to install the floating_ip zip archive. What can I do to get the script running correctly?

**Comment by svensp** [comment]
It seems the gist for the auto install was both outdated and broken. I updated the gist and the documentation linking to it. Please try again with the following command:
```
curl 'https://gist.githubusercontent.com/svensp/1065ac4cbf9873a10eda7b85d4b5d07f/raw/fc048c2c1688f97d1507fd1d1a5a53d14c794976/install_hcloud_floating_ip.sh' | sudo sh
```

If you still have problems then please run the following command and post its output here
```
/usr/lib/ocf/resource.d/hetzner/floating_ip meta-data
```

**Comment by ahaase-moditech** [comment]
Installation with newer version for floating_ip worked, but the error stays the same. I attached meta-data.txt containing output of the command you mentioned.
[meta-data.txt](https://github.com/svensp/hcloud_ocf/files/3836916/meta-data.txt)

**Comment by ahaase-moditech** [comment]
In /usr/lib/python3/dist-packages/crmsh/ra.py I removed the try-exception block starting at line 631 and just generated the value of the xml variable. Doing so, I get the error message "Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.". Looking into the metadata.xml, there is an encoding declaration, that is not in all other ocf resource agents. Maybe this is the problem? How can I remove the encoding temporarily for testing this?

**Comment by svensp** [comment]
The meta-data declaration matches the one I have working on my hosts.

What version of pacemaker are you running? Also seeing your mentioned file you're using crmsh. I have only tested the agent using pcs so far. So please also post the command which gives you the error, masking any credentials if necessary of course.

If you want test your own changes simply clone the repository and run `./build.sh` inside the repository root. It will create build/floating_ip as executable file.

**Comment by ahaase-moditech** [comment]
I'm running pacemaker 2.0.1-5 and crmsh 4.0.0 on a Debian Buster installation. The errors gets displayed when trying to get the ra infos:

`root@host1:~# crm ra info floating_point
ERROR: ocf:heartbeat:floating_point: got no meta-data, does this RA exist?`

When trying to add the ip primitive, the error looks very similiar:

`root@host1:~# crm configure
crm(live/host1)configure# primitive resIP ocf:hetzner:floating_up params ip=x.x.x.x api_token=yyy
ERROR: ocf:hetzner:floating_up: got no meta-data, does this RA exist?`

But of course, the script is placed in the correct folder:

`root@host1:~# ls -l /usr/lib/ocf/resource.d/hetzner/floating_ip
-rwxr-xr-x 1 root root 61481 Aug 19 15:22 /usr/lib/ocf/resource.d/hetzner/floating_ip`

**Comment by svensp** [comment]
Are those the original commands you ran or reconstructions? They both contain typos:

`root@host1:~# crm ra info floating_point` should be `root@host1:~# crm ra info ocf:hetzner:floating_ip` -> if you don't specify the type and vendor it will look for ocf:heartbeat which is the default but the agent is not installed in the heartbeat directory

and 

`primitive resIP ocf:hetzner:floating_up` should be `primitive resIP ocf:hetzner:floating_ip`

**Comment by ahaase-moditech** [comment]
Hmpf :-) ... ok, corrected the commands, the errors keep getting thrown:

> root@host1:~/hcloud_ocf# crm ra info ocf:hetzner:floating_ip
> ERROR: ocf:hetzner:floating_ip: Cannot parse meta-data XML
> ERROR: ocf:hetzner:floating_ip: got no meta-data, does this RA exist?

And same for configuring the primitive:

> root@host1:~/hcloud_ocf# crm configure
> crm(live/host1)configure# primitive resIP ocf:hetzner:floating_ip params ip=x.x.x.x api_token=yyy
> ERROR: ocf:hetzner:floating_ip: Cannot parse meta-data XML
> ERROR: ocf:hetzner:floating_ip: got no meta-data, does this RA exist?

**Comment by svensp** [comment]
Okay, that points towards pacemaker 2 since all my instances are currently running with pacemaker 1.x

I'll spin up a new machine and see if I can replicate this error with pacemaker 2

**Comment by ahaase-moditech** [comment]
That would be great. In the meanwhile, is there an easy way to omit the encoding in the xml header? Removing the encoding='UTF-8' in ocf.py line 91, only leads to encoding='ASCII' in the resulting XML, which isn't accepted by crmsh as well.

**Comment by svensp** [comment]
I was able to confirm the problem on pacemaker 2.

Removing the encoding as you suggested indeed fixed it for me and let me run `crm ra info ocf:hetzner:floating_ip` successfully. I build a new version `1.2.2` and updated the auto install script so it will be installed in the future. Please try it out and report future issues so I can update the agent to work with pacemaker 2

On that note: it seems python ET.tostring does not support not adding the encoding so I used string replace to remove it. It's ugly. But it works.

**Comment by ahaase-moditech** [comment]
Works great now. Thank you very much for your assistance.
